apiVersion: v1
kind: Service
metadata:
  name: admission-predictor-service
spec:
  selector:
    app: admission-predictor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
